### ISSUE TITLE
Prepare an 0.8.1 release

### ISSUE THREAD

**Issue by jsirois** [wickman/pystachio#22]

**Comment by jsirois** [comment]
This should at least include #19 and it would be nice to include an implementation of #17 as well.

**Comment by mauri** [comment]
any ETA for this release? super interested in #19 :)

**Comment by jsirois** [comment]
@mauri - certainly by EOW (April 1st); hopefully earlier.

**Comment by jsirois** [comment]
This got delayed a bit.  Forgot I had the [pants release](http://pantsbuild.github.io/changelog.html) to do today!

**Comment by dctrwatson** [comment]
Looking forward to this release! Hate to be a bother, but curious about an ETA update?

**Comment by jsirois** [comment]
I'll release by tomorrow AM if I still can't find a nice way to have `Choice` fields materialize as their underlying type.  Worst case if I can't figure this out in time is a 1.0.0 API-breaking release that includes the improvement.

**Comment by jsirois** [comment]
Alrighty, I'm going to give up on perfecting the `Choice` read-api since the write api that will be much more widespread looks good.  The fact that we're pre-1.0.0 also gives some latitude to allow 0.8.x or 0.9.x to contain an API break (assuming [semver](http://semver.org/)).

**Comment by jsirois** [comment]
Not including #17

**Comment by jsirois** [comment]
Released:
https://github.com/wickman/pystachio/releases/tag/v0.8.1
https://pypi.python.org/pypi/pystachio/0.8.1
