### ISSUE TITLE
Pystachio performance issues

### ISSUE THREAD

**Issue by monjaro** [wickman/pystachio#24]
We recently started using pystachio for some configuration at our company, and it struggles on large configs. We have configs that can take ~10s to `check()`. Based on some preliminary benchmarking and reading of the source, it appears that pystachio will re-evaluate certain functions (e.g.: `scopes`, `check`, etc) many times on the same objects, despite the fact that the objects are treated as immutable after creation.

Would you accept a patch to memoize or otherwise eliminate these redundant computations?

**Comment by StephanErb** [comment]
While I cannot speak or the maintainers, I'd be interested in such an improvement as well +1.

/cc @jsirois

**Comment by jsirois** [comment]
@StephanErb @monjaro, agreed - this would be a welcome patch.

**Comment by StephanErb** [comment]
As I have bumped into some Pystachio perf issues recently again (after 2 years!) and have opened the PR https://github.com/wickman/pystachio/pull/32 to address them.

**Comment by jsirois** [comment]
Released!: https://pypi.org/project/pystachio/0.8.5/#files
Thanks @StephanErb for the perf fix.
