### ISSUE TITLE
Extend Ref to allow some special characters

### ISSUE THREAD

**Issue by shanmugh** [wickman/pystachio#26]
Today Ref object only allows alphanumeric values and starting with alphabets for DEREF and alphanumeric values and '-' for INDEX, which is too restrictive.

  _DEREF_RE = r'[^\d\W]\w*'
  _INDEX_RE = r'[\w\-]+'
  _REF_RE = re.compile(r'(\.' + _DEREF_RE + r'|\[' + _INDEX_RE + r'\])')

We are looking to use Pystachio's binding to create a Docker binding helper that would resolve 'name:tag' combinations to 'name@digest' to create a concrete identifier. Where the 'name' can contain '/' and 'tag' can contain '.'.

We would like to extend the allowed characters for DEREF and INDEX to accommodate Docker image name and tag values. See https://github.com/docker/distribution/blob/master/reference/reference.go for full definition of docker image references.

**Comment by shanmugh** [comment]
https://github.com/wickman/pystachio/pull/27

**Comment by jsirois** [comment]
I'll leave this open until I cut a pypi release here ~presently.

**Comment by jsirois** [comment]
Released here: https://pypi.python.org/pypi/pystachio/0.8.3

Thanks @shanmugh!
